### ISSUE TITLE
Readme and gitignore

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YC.BioGraph#1]
При инициализации репозитория я бы рекомендовал сразу генерировать правильный gitignore для студии (так и называется: VisualStudio) и Readme. Если Readme ещё несложно создать руками, то gitignore штука ценная и помогает избежать случайного попадания всякого хлама в репозиторий.

**Comment by MallabaevAzamat** [comment]
Вопрос вроде бы решён вами. По поводу .gitignore мы обсуждали в #5.
Лучше всё же оставлять .gitignore от ProjectScaffold'а там есть раздел о paket'е и он сам по себе аккуратнее выглядит.

**Comment by gsvgit** [comment]
Да, согласен. Лучше оставлять от ProjectScaffold'а.
